# Site settings
name: Sagar raikar
title: Sagar Raikar | Software Engineer
description: Software engineer focused on building beautiful interfaces and experiences
url: https://raikarsagar.github.io/
baseurl: ''
email: raikarsagar007@gmail.com
cover: https://raikarsagar.github.io/img/og.png
logo: https://raikarsagar.github.io/img/emojis/technologist.png
resume: https://raikarsagar.github.io/resume.pdf
social:
  - title: email
    url: mailto:https://raikarsagar.github.io/
  - title: twitter
    url: https://twitter.com/raikarsagar97
  - title: instagram
    url: 
  - title: codepen
    url: 
  - title: github
    url: https://www.github.com/raikarsagar
  - title: linkedin
    url: https://www.linkedin.com/in/raikarsagar

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
